language: java

dist: trusty

jdk:
  - openjdk8

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true

env:
  global:
  - secure: hkCbmI6DIipcU4fkYHoGV3Elen479+2pQS9ZbIWIwiRddcCIBzhZecaU3CQvp+sOlBPFb4cJLwJuds2kfvjFbtKpWESkTdBVgS29+fTfpQFGDW1Ph6Vjokc9FAi3FLCfF/mq4O54jOiipAIxZIcojgfbrUThxQQDcJrOC3U1OvDsC8riLLrFT9ovhS2Zr1XiA03a2cG5MpLStjiYIUQtJh11olOO7jGYShDMgHoiAE9FCQxhrK54b1pW2N0elD2p6LI0+B08fApWwUqAUyyp/IYKMi0W9bLLniNfjE6tbue9W1KqIgyGnMgJoVV2lMEHwhdkWyg0JZFOJTT0+4xpUG7Yp9AqiNRVljmcR+/HHMt7SrtoN//FhXPL785Y2k83PuQ+J2226AYM626KOtECdfyArABvPwyZ54G6HjoTwD9z5rEj2IKRuiFabHovaew+bm9Ng023o+Zri0TspDUhNCx/yT07IpgVc6KicyMKw3mEztjngIgcp7D3zRrMisZbUguwNMmE62vRtWsg1sd6VWPUKm1W7ZW/wV72VK5FMga++11kIciq0Ntf3hKiOpKgJ6nO/mfJprNIV9hO9X8CxPU8ahPAixx4PKWGfyuwV8hC0pwu24psL9WFR8ae/ocvGpq3d9x33rX013zuBuNnIA+FmDmg1LDEhiNlrnbx87o=
  - secure: YzU9XKVkw14NDnamVi/PJ3hApQ00b5GHjKndlle6bve2fvD1LTEB6ctnS3aLYsgILuxUA9d1wxZr/r2EaMnbBRdoI5UL1cvvBgZyr/+AWbC1WTYwzhRAx1KjwxYbM44u7jE/tYOE2CR2QIDBSbKuiR+Aj7IX2pMiO/u0DHt4sB3a6EKsjA8r1fn6p4dd4AGmTTlbw/7sqi5K+4ACcyQ3jWG4PHox/9yGt6GmsPxoh7TS5V329GyL3HtJSpAICrxybZ3iesruPs4Bs0hJjWvCWDQS0JyPzcqFtnInWhdk2t0820YmMq47h2UvjWGffqscvHRxFt0eW5RoKBnasehbbko0X7qMOapXyS84zjNvgP6engoH6IX7X6NopJzsmtRVUAq2YZQIoQiDzzIOTw2Z2cTyROsVq3iRmri1qOBGS/I2bM+pYqj1kpp69E1SpdGnIAN1MaGepY3k2ATCQqwKIxnrb2iMxkPToUseTNFT26uZ2xw0Gj/XWzJRwamWMHLshc26IdqAzJ/WVKfrTiullJIAeRmW7F6tfp1Z00mrwDMJToQgnkQFaxXGzhnze6NDRCqINgpSZbYxl1NpJSJqX74l0Qig6k+4sbHOqsn6TvulPatSSVsg+SjeKoNgUgE6vkXQqDgFEfA0SMr0MkoJbVxziBiteOFFftiJVCojhuY=
