language: java
dist: trusty
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
  skip_cleanup: true
env:
  global:
  - secure: PEsZbKRqeAWAdwkTBGNoJsqzNayOM/tNvjRbwpXOLjaWDC+f8zExOezTjm0zRpVUwLwqRt3v/cKaIAEaKLZdBuZMal7LdxxnIjuqNaQ5X5I5ZcmSqv8uVkmQnj7yPVVlyfwG9DCuLKLjjuqEcOwSqitoXdyhWgCRqi5A3CAyO+ut1W3iFlZKuO9xLR+jIEkXhbwNjfLUUxtxWHU9a+akpxaTUrjz3ItuaYDxByHTFtv33UdATzHPoUnjYjdrrbMZzd3xLY/eib7H8YoSem0R0xIpuezSRLqtKM+tppBwOTpLNUExWBZoCjD+oEpbDXWTrOZfv5rZ6hFN77QScv2cv9MBs025grYuMibPy07isZ7sXKjUyBs+QPJby2sucSdumsYGwd90XDXtjqAw7sbzW/ka9yU1ALocgxWeQXWej8pF+x1cuDv2GUNIigTmhbXJcLPpwgPDSqd7UAVW+BUoFPfZ54a4SzI3ZO97nfe+9Z1lN/C7zkH2TIQK1IK2loWj5Fg8vOFUFGuJjXDVxNO/qy5mF+I9yovAWicyyCddcMUP/SRrMbIgUpzPwshEDOVL811hRumQwhcaCaegJEXTmDuNmplgq0VgdJ/hQQHkAE+E16dQ4tNjyVPINEuatuysuLzAwMBHQu2GJS3Xvc7tBvBb5pSBT7blSwJN0teEroA=
  - secure: Fb2t+lf5wSMKZLluMLkztoVRBrTct/kWOmQ9D/l428yBB5oPcx0PCJiLgk9NG5e4eFDvLekd0TkGOJKTz3kcQ5l5R0seKPqKbd1Z4X2iKXn131XWXEAP7ce86f5RSPRE/OYXgg3/jQkFYCnlRws4SImnHLawnyFgenzu4DpGleRDRF2Uko8miBg0lMB/P+dN9LBpnxFTNiVlQFOXkNvyFf4mu3zyWUkvlhPi3AUnOQE63yrtPFfqOqO2lG1TQ1/D2bvNm4Ivi+MHku5MhhHEmwIMVPwu9X4tPhLZSPGTG6KL9/TcmJtciqRKuB/ym0cyw5Mvjqc8jVSBOi3tGDH2DM6BnxIIlbB/X9Xbl580232xU0vMyA+sjEe7MKWtRSl7CcTSMdcycfzPn5/06T4IdtDd6HKYl69m7J7asl+QHCije6qbV7KKd8xgYDhlLdla3mG9i9LpbSsukatoGo6hbSxuM6RcmScduqJFQo8Egv3VEV6j7hWgdzRZOR2wBNP43VTulWj3h78KIxdCyMDxNG8KlttDXR3c7AyeGivE3MtbZOPi4PjPw+ctgoNmkFjigQB+SzpZBexfrSYXg5M/xkY5pexhLgffwa57MsuVfM8Kdb0/ZDusnxvPsOXcAmpNY2KiP+Zrfhgt+24wDP1eNmx4aJ3jWJE4YumHEou1DqQ=
notifications:
  slack:
    rooms:
      secure: EA4svd0wLV362hvtVy1qilIw5A42AvEjNvEIAcTgXpZyNXMrfitnFEI0F7uyRmkPrUJDS/eGTFLlZYZEStwH+iMJzonlhsYu8Ef8/icLCV1oPzgVnYH+g95ShTyWwbzhfa1WxkQ94h/wZRtqnFTs9OQbJ22MOLuC1LMtMRSSP71JP0+/K11n3h9s+SrwVijzyLuKTybIIdnuWCN+S1uALWyHp9TMc/GoSJRl9Ff4DWmnihyWEWFg1YTtK8WBWjvDipxZGOxAUQbFrfWo1IodNxYmT9t9+Z1fUtQ06S55lNhody6+uzpi9UoMYiKv+ol4iUe0iLGpyUNKnAeXHOspLThiYIggs9IXmj7QlxGS5oHbroPxQ+sumaAkFoFyfoGSbZQO3ukKQcHRLbr15JK30IgoC5gwf3gZlEy2TncHDqV7HEryqgYCElD/Us7pwOgrOwLKW7Jojjmx2EYnsjfdPspJ6pl/RI7NYQhePwovG3HyD6fqy7yhfKaDI2ygUpAyCYjMC24ap/cYs8ko9mZ0CpFPZPZjgp3WTL244ROMQ4KHclAGC/oaw2S30OLQ5CTLrDJrzQjWjDQeieIE5eKrW2UmdS/r7CFDE0CSkEBwiuiU92GKolhBn/o2yCG8FSBeknMDHu4JioQCbAJBZyAZfFEzJEb7PUUq08PtA+GEsyM=
